[34m[1mwandb[39m[22m: [33mWARNING[39m Ignoring project 'Fagprojekt' when running a sweep.
[34m[1mwandb[39m[22m: [33mWARNING[39m Ignoring entity 'lyngsberg-danmarks-tekniske-universitet-dtu' when running a sweep.
/home/lyngsberg/fagproject/02466_project/fagproject/src/project/sweep_train.py:69: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  x, y = torch.load(data_path)
Traceback (most recent call last):
  File "/home/lyngsberg/fagproject/02466_project/fagproject/src/project/sweep_train.py", line 185, in <module>
    train_model()
    ~~~~~~~~~~~^^
  File "/home/lyngsberg/fagproject/02466_project/fagproject/src/project/sweep_train.py", line 69, in train_model
    x, y = torch.load(data_path)
           ~~~~~~~~~~^^^^^^^^^^^
  File "/home/lyngsberg/miniconda3/envs/fagprojekt/lib/python3.13/site-packages/torch/serialization.py", line 1319, in load
    with _open_file_like(f, "rb") as opened_file:
         ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/lyngsberg/miniconda3/envs/fagprojekt/lib/python3.13/site-packages/torch/serialization.py", line 659, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/lyngsberg/miniconda3/envs/fagprojekt/lib/python3.13/site-packages/torch/serialization.py", line 640, in __init__
    super().__init__(open(name, mode))
                     ~~~~^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'fagproject/data/train_c_n_1'
Using device: cuda